FROM node:23.11-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV WATCHPACK_POLLING=true
RUN corepack enable

WORKDIR /app

COPY package.json  package-lock.json* pnpm-lock.yaml* ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY src ./src
COPY public ./public

COPY next.config.js .env .env.development tsconfig.json .prettierrc.yaml .eslintrc.json components.json  \
     next-env.d.ts  \
     tailwind.config.ts tailwind.config.js postcss.config.js /app/

CMD pnpm dev