FROM node:23.11-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json  package-lock.json* pnpm-lock.yaml* ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile


COPY src ./src
COPY public ./public

COPY next.config.js .env .env.development tsconfig.json .prettierrc.yaml .eslintrc.json components.json  \
     next-env.d.ts  \
     tailwind.config.ts tailwind.config.js postcss.config.js /app/

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
# ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager
CMD pnpm dev