services:

  data-studio-api:
    container_name: data-studio-api
    build:
      context: ./backend
      dockerfile: ./docker/prod.Dockerfile
    entrypoint: /app/docker/server-entrypoint.sh
    env_file: .env
    expose:
      - 8000
    depends_on:
      - data-studio-redis
      - data-studio-db
    restart: always
    networks:
      - shared-network

  data-studio-celery-worker:
    container_name: data-studio-celery-worker
    build:
      context: ./backend
      dockerfile: ./docker/prod.Dockerfile
    entrypoint: /app/docker/celery-entrypoint.sh
    env_file: .env
    restart: always
    expose:
      - 5555
    depends_on:
      - data-studio-api
      - data-studio-redis
      - data-studio-db
    networks:
      - shared-network

  data-studio-redis:
    container_name: data-studio-redis
    restart: always
    image: redis:7.2-alpine
    expose:
      - 6379
    networks:
      - shared-network


  data-studio-db:
    image: postgres:15.5-alpine3.19
    volumes:
      - data-studio-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGSSLCERT=${PGSSLCERT}
    networks:
      - shared-network


  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    container_name: adhoc-postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    networks:
      - shared-network  # Same network as monitoring stack
    depends_on:
      - data-studio-db

  redis-exporter:
    image: oliver006/redis_exporter:v1.74.0-alpine
    container_name: adhoc-redis-exporter
    restart: always
    environment:
      REDIS_ADDR: "redis:6379"
    networks:
      - shared-network
    depends_on:
      - redis

volumes:
  data-studio-db-data:
    name: data-studio-db-data
    driver: local

networks:
  shared-network:
    name: shared-network
    driver: bridge
    external: true

