services:
  data-studio-ui:
    container_name: ${PROJECT_NAME}-ui
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    expose:
      - 3000
    networks:
      - shared-network

  data-studio-api:
    container_name: ${PROJECT_NAME}-api
    build:
      context: ./backend
      dockerfile: ./docker/dev.Dockerfile
    entrypoint: /app/docker/server-entrypoint.sh
    volumes:
      - ./backend/src:/app/src/
      - ./backend/docker:/app/docker/
    env_file: .env
    expose:
      - 8000
    ports:
      - "8989:8989"
    depends_on:
      - data-studio-redis
      - db
    restart: always
    networks:
      - shared-network

  data-studio-celery-worker:
    container_name: ${PROJECT_NAME}-celery-worker
    build:
      context: ./backend
      dockerfile: ./docker/dev.Dockerfile
    entrypoint: /app/docker/celery-entrypoint.sh
    env_file: .env
    volumes:
      - ./backend/src:/app/src/
    restart: always
    expose:
      - 5555
    depends_on:
      - data-studio-api
      - data-studio-redis
      - db
    networks:
      - shared-network

  data-studio-redis:
    container_name: ${PROJECT_NAME}-redis
    restart: always
    image: redis:7.2-alpine
    expose:
      - 6379
    networks:
      - shared-network

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: ./backend
      dockerfile: ./docker/nginx/nginx.Dockerfile
    volumes:
      - ./backend/certs:/etc/ssl/certs/:ro
    env_file: .env
    ports:
      - 443:443
    networks:
      - shared-network
    restart: always
    depends_on:
      - ${PROJECT_NAME}-api
      - ${PROJECT_NAME}-celery-worker

  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:15.5-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGSSLCERT=${PGSSLCERT}
    networks:
      - shared-network

volumes:
  db_data:
    name: db_data
    driver: local

networks:
  shared-network:
    name: shared-network
    driver: bridge
    # external: true
